name: feapi
description: "Personal Finance Tracker"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.3.0+1

environment:
  sdk: ^3.13.4
  # dependensi lain

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_3_expressive: ^1.1.5
  # dependensi lain
  sqflite_common_ffi: ^2.4.0+2
  flutter_riverpod: ^2.5.1
  csv: ^6.0.0
  path_provider: ^2.1.2
  share_plus: ^13.3.0
  encrypt: ^5.0.3
  # file_picker: ^8.0.0
  file_picker: ^13.1.0
  fl_chart: ^0.69.0
  ## Sync gdrive
  google_sign_in: ^6.2.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.2.0
  path: ^1.9.0
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  flutter_secure_storage: ^11.2.0
  image: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.8
  # dependensi lain

flutter:
  uses-material-design: true
  fonts:
    - family: "SN Pro"
      fonts:
        # File font utama (Tegak)
        - asset: assets/fonts/SNPro-VariableFont_wght.ttf
        # File font kedua (Miring) - harus diberi label style: italic
        - asset: assets/fonts/SNPro-Italic-VariableFont_wght.ttf
          style: italic
