name: feapi
description: "Personal Finance Tracker"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.13.4
  # dependensi lain

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_3_expressive: ^1.1.3
  # dependensi lain
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.8
  # dependensi lain

flutter:
  uses-material-design: true
  fonts:
    - family: "SN Pro"
      fonts:
        # File font utama (Tegak)
        - asset: assets/fonts/SNPro-VariableFont_wght.ttf
        # File font kedua (Miring) - harus diberi label style: italic
        - asset: assets/fonts/SNPro-Italic-VariableFont_wght.ttf
          style: italic
